from odoo import fields, models, api, _
from odoo.exceptions import ValidationError


class productTemplateInherit(models.Model):
    _inherit = 'product.template'

    @api.model
    def default_get(self, fields):
        res = super(productTemplateInherit, self).default_get(fields)
        res['branch_id'] = self.env['res.branch'].search([('name', '=', 'Sidoarjo')]).id
        return res

    is_roll = fields.Boolean(string="Is a Haspel?", default=False)
    is_in_autogenerate = fields.Boolean(string="Lot Number Auto Generated By System", default=True)

    product_classification_id = fields.Many2one('product.classification', string="Product Classification")
    product_detail_id = fields.Many2one('product.detail', string="Product Detail")

    branch_id = fields.Many2one('res.branch', string='Branch', default=lambda self: self.env['res.branch'].search([('name', '=', 'Sidoarjo')]))

    @api.constrains('default_code')
    def _check_constrain_default_code(self):
        if self.default_code:
            all_default_code = [code.default_code.lower() for code in self.env['product.template'].search([('id','!=', self._origin.id)]) if code.default_code]
            if self.default_code.lower() in all_default_code:
                raise ValidationError(_('Product Code must be unique.'))